### ISSUE TITLE
Discourse

### ISSUE THREAD

**Issue by kmuehlbauer** [openradar/openradar.github.io#11]
Great News!

:tada: https://openradar.discourse.group/ :rocket: 

We are online with discourse. I've added a general welcoming post, but now we all have to engage and fill the void. Please sign up and I'll distribute the privileges.

**Comment by kmuehlbauer** [comment]
@mgrover1 After resetting credentials I've just enabled github sign-in on the discourse.

**Comment by mgrover1** [comment]
> @mgrover1 After resetting credentials I've just enabled github sign-in on the discourse.

✅ Account created

**Comment by kmuehlbauer** [comment]
@mgrover1 You are in, granted Moderation/Admin.

**Comment by kmuehlbauer** [comment]
I've transferred the Github oauth app to openradar organization.

**Comment by kmuehlbauer** [comment]
Let's discuss everything else connected with discourse over there. Now that we have it. Thanks discourse team!
