### ISSUE TITLE
Add pyhail to the list of openradar packages

### ISSUE THREAD

**Issue by mgrover1** [openradar/openradar.github.io#13]
@joshua-wx - would you be interested in adding pyhail to the list of open radar packages?

From your side, you would need to add a `pyhail.md` file to this directory https://github.com/openradar/openradar.github.io/tree/main/posts/packages

It would also be neat to add a blog post introducing the package to the community, similar to this post [new look to open radar post](https://github.com/openradar/openradar.github.io/blob/main/posts/2022/new-theme-announcment.md), which renders on the site [here](https://openradarscience.org/blog/)

**Comment by joshua-wx** [comment]
sure! I'd be happy to contribute this. I'm on leave this week and will get onto it next week :)

**Comment by joshua-wx** [comment]
Hey, I've completed the new pages. I can't push my local branch. Did you want me to fork first then do a pull request?

**Comment by mgrover1** [comment]
Yes, that would be great!
