### ISSUE TITLE
Refresh openradarscience.org landing page

### ISSUE THREAD

**Issue by kmuehlbauer** [openradar/openradar.github.io#17]
Currently we have the openradarscience landing as this:

https://openradarscience.org/

There we have a short overview on Open Science, the affiliated packages (blog-like) and a blog with some news.

As https://openradar.discourse.group/ is our central discussion and news advertising point I've taken the chance to give a clean-up a try, removing the blog and moving to the new myst build:

https://kmuehlbauer.github.io/openradar.github.io/

This new site should be very much static, only the packages/projects listed are about to change. We might even think about removing the individual package/project sites and just set links to their respective landing pages. That way this site would be a very informative overview, which can be adapted every once in a while.

@openradar/developers WDYT?

**Comment by mgrover1** [comment]
I like the new myst look! Much better than traditional sphinx; I also agree just linking is the better approach as it reduces the technical debt of maintaining duplicated information!

**Comment by kmuehlbauer** [comment]
OK, I'll try to come up with a solution without overcrowding navigation.

Maybe using `grids` and `cards`...

**Comment by zssherman** [comment]
@kmuehlbauer I think the new docs look great!

**Comment by kmuehlbauer** [comment]
@openradar/developers Please revisit the renewed page and open issues and/or pull requests to fix/add anything you spot.

**Comment by kmuehlbauer** [comment]
resolved by #19 ff.
