### ISSUE TITLE
Organization logo

### ISSUE THREAD

**Issue by kmuehlbauer** [openradar/openradar.github.io#8]
Inspired by the ERAD2022 logo I thought it would be nice to have our own simple openradar/openradarscience logo.

How about 

![openradar_small](https://user-images.githubusercontent.com/5821660/188607759-5ddda8b5-1db4-42a1-943a-11b2c983831f.svg)

and

![openradar](https://user-images.githubusercontent.com/5821660/188577011-72b0f1ab-30eb-4e81-9992-6ef621af1126.svg)

and

![openradarscience](https://user-images.githubusercontent.com/5821660/188577385-c1af50f8-10cc-4c04-b108-a7a43a5d3a3f.svg)

What do you think @openradar/owners?

**Comment by scollis** [comment]
I like the concept! I would replace the R with a simple tower structure or the E dashes.. otherwise folks might think we code in R :) You could also use the dome as the "o"

**Comment by scollis** [comment]
![Screen Shot 2022-09-06 at 7 54 04 AM](https://user-images.githubusercontent.com/825351/188640433-ac0c8e76-936d-4f24-984c-8c4f872839e9.png)

**Comment by kmuehlbauer** [comment]
![openradar1_small](https://user-images.githubusercontent.com/5821660/188648971-2c241d48-2364-4e81-a8c0-c4a28dc590df.svg)


![openradar1](https://user-images.githubusercontent.com/5821660/188649010-0a7c13b0-0072-4625-abec-255fbadbc735.svg)


![openradarscience1](https://user-images.githubusercontent.com/5821660/188649031-ac29b420-cdd5-4907-b90e-26e9751cdadd.svg)

I've tinkered with using the Radome as O, but that doesn't look very nice. The remaining `PEN` gets easily read as pen like in pencil.

**Comment by kmuehlbauer** [comment]
![openradarscience1](https://user-images.githubusercontent.com/5821660/188657814-b2e1e9d8-ba87-453f-a433-5278569f8417.svg)

Dark/Light-mode friendly color.

**Comment by kmuehlbauer** [comment]
If there is interest to see this live, I would equip one of the openradar sites with an example. Maybe I just go for it and we can tweak/adapt from there.

**Comment by kmuehlbauer** [comment]
This can be used as favicon (browser tab) or where not much place is available. The OR for Open Radar is nicely seen also in situations where the svg is scaled to a minimum:

![openradar_micro](https://user-images.githubusercontent.com/5821660/188807580-f6b0aa33-b901-4b4a-accc-5f2255fbfb36.svg)

This can be used as icon link or any other situation:

![openradar_mini](https://user-images.githubusercontent.com/5821660/188807757-6881e02e-b6b6-463c-b867-5704e04a237a.svg)

This would go as the normal logo, without the `OR` the logo is more simplistic:

![openradar_logo](https://user-images.githubusercontent.com/5821660/188807999-39f1343e-7471-443d-be47-58098d963aa2.svg)

You can see it in action in this PR https://github.com/openradar/openradar-docs/pull/2. The rendered output is here https://openradar-docs--2.org.readthedocs.build/en/2/

**Comment by kmuehlbauer** [comment]
The xradar site was just updated:

https://docs.openradarscience.org/projects/xradar/en/latest/

Shall we move forward with this?

**Comment by mgrover1** [comment]
I like the non-OR one... the last option you included there. It looks great on the website!

**Comment by kmuehlbauer** [comment]
Final? Versions...

![openradar_micro](https://user-images.githubusercontent.com/5821660/190074447-386ec059-2edb-495f-8d7f-c6b67192dd58.svg)
![openradar_mini](https://user-images.githubusercontent.com/5821660/190074475-593cd64d-e6b3-49f3-bcb9-c8a0d1729cb4.svg)
![openradar_logo](https://user-images.githubusercontent.com/5821660/190074495-39bc4ab6-a011-4255-8961-adb2d3c6b856.svg)

**Comment by kmuehlbauer** [comment]
Please reopen, if necessary
